### ISSUE TITLE
Error: An action "monthAction" does not exist in controller "GeorgRinger\News\Controller\NewsController".

### ISSUE THREAD

**Issue by bzgaLindner** [georgringer/eventnews#132]
Hi,
I still get this Error with News 9.2.0 and eventness 5.0.0, installed both from scratch and set up new month view:

>     An action "monthAction" does not exist in controller "GeorgRinger\News\Controller\NewsController".

I know there was a discussion about this, but it seems toe have been closed without solving this issue, so I want to make sure it does not get lost.

Thanks, 
Dominik

**Comment by bzgaLindner** [comment]
Seems like extending news 9.2.0 with eventnews 5.0.0. does not work at all.
Copying controller actions from eventnews into GeorgRinger\News\Controller\NewsController.php and template Month.html to EXT:news/Resources/Templates/News/Month.html does help (but is not a solution, of course).

**Comment by kitzberger** [comment]
Can confirm that bug with TYPO3 10.4 and news 9.0, eventnews 5.0.0.

Switching to the list plugin makes the "event news records" show up and their event specific fields do work.

Btw. the cache file `tx_news_controller_newscontroller.php` does contain the monthAction, the whole class is just not being used. So it seems....

**Comment by georgringer** [comment]
couldn't reproduce that. does adding the Controller dir at https://github.com/georgringer/news/blob/main/Configuration/Services.yaml#L18 help in your projects?

**Comment by kitzberger** [comment]
@georgringer, unfortunately not ;-/

When I add `var_dump($cacheEntryIdentifier);` into ClassLoader->loadClass() it only outputs there:
* string(25) "tx_news_domain_model_news"
* string(44) "tx_news_domain_repository_categoryrepository"
* string(24) "tx_news_domain_model_tag"

**Comment by bzgaLindner** [comment]
@georgringer: does not work with 

exclude: '../Classes/Domain/Model/*, ../Classes/Controller/*'

in EXT:news/Configuration/Services.yaml, line 18

**Comment by BastianBalthasarBux** [comment]
Exactly the same here.
None-composer Setup.

**Comment by buepro** [comment]
When adjusting `EXT:eventnews/Configuration/Services.yaml` as below it works on by side ...

```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Eventnews\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  GeorgRinger\News\Controller\NewsController: '@GeorgRinger\Eventnews\Controller\NewsController'
```

Would `ext_localconf.php` need to be adapted as well? E.g. remove

```
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Model/News'][] = 'eventnews';
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Controller/NewsController'][] = 'eventnews';
```

@georgringer if you see this could splve it I could provide a PR.
