### ISSUE TITLE
Route Enhancer

### ISSUE THREAD

**Issue by hweckhardt** [georgringer/eventnews#75]
I am using eventnews 3.0.0 and the route enhancer of the news extension. Everything works fine, with one problem. The previous/next month link (above the calendar) is put together from the page url plus the year/month, and leads to a 404 exception, as this page does not exist. Is there a workable route enhancer for eventnews available?

**Comment by janslu** [comment]
For anyone looking for an updated config for Eventnews v6:

```
 NewsEvents:
    type: Extbase
    extension: Eventnews
    plugin: Newsmonth
    routes:
      - routePath: '/year/{date-year}/month/{date-month}'
        _controller: 'News::month'
        _arguments:
          date-month: 'overwriteDemand/month'
          date-year: 'overwriteDemand/year'
        requirements:
          date-month: '\d+'
          date-year: '\d+'
    defaults:
      date-month: ''
      date-year: ''
    aspects:
      date-month:
        type: StaticRangeMapper
        start: '1'
        end: '12'
      date-year:
        type: StaticRangeMapper
        start: '2000'
        end: '2040'
```
